### ISSUE TITLE
Notion of CQRS

### ISSUE THREAD

**Issue by jaredcnance** [Research-Institute/json-api-dotnet-core#125]
It should be straightforward to implement query only endpoints without having to implement all members of `IResourceService` or `IEntityRepository` and throwing NotImplementedExceptions. This issue is a placeholder until I can work out the design.

#### 2017-6-11

This work is going to be done on feat/cqrs branch and available as pre-release v2.1.0-alpha1-*

#### 2017-6-30

The current version is available on the unstable branch and can be installed from this [MyGet feed](https://www.myget.org/feed/jadnc/package/nuget/JsonApiDotNetCore). If everything goes well, I plan on wrapping up tests this weekend and pushing to NuGet as a beta.

**Comment by jaredcnance** [comment]
### Brain Dump
I think the above proposal is okay, but it still means that some services may end up have `NotImplementedException`s. The only way I see around this, is to fully segregate the service interfaces by method.

**Comment by williamwong** [comment]
I like the idea of the proposal overall, but two questions:

1. In general, my service layer doesn't interact with Entity Framework at all. I interact with the entities using just the IEntityRepository interface. Is there a way to implement the custom service as you've described above without "leaking" the DbContext into the service layer?
2. What's the advantage of having the endpoints enum rather than using C# attributes on the controller, which seems to be the general convention for describing which HTTP methods are supported?

**Comment by jasolko** [comment]
@williamwong it looks to me like the DbContext is being used specifically in the example implementation of the MyReportService and isn't required by any base class. Any concrete implementation would be able to define its own dependencies.

I also wonder what the reason is for the endpoint enums over using attributes on the controller?

With the interfaces segregated this way and by defining what methods are supported on the controller is there still a reason to also have separate Cmd/Query Controller/Services?

**Comment by jaredcnance** [comment]
@jasolko that's correct. 
> What's the advantage of having the endpoints enum rather than using C# attributes on the controller, which seems to be the general convention for describing which HTTP methods are supported?

> I also wonder what the reason is for the endpoint enums over using attributes on the controller?

The enums were chosen for simplicity of implementation and to reduce reflection. But, I am wondering if that is even needed. Technically, this means the available endpoints have been defined twice, once in the resource controller and then again in the base class constructor. This is probably not necessary.

> With the interfaces segregated this way and by defining what methods are supported on the controller is there still a reason to also have separate Cmd/Query Controller/Services?

I'm not certain. From the controller standpoint, it would be a quick way to implement it without having to explicitly define the method signatures yourself and that is the only advantage I see.

Regarding the services, these interfaces would just allow for fewer parameters in the constructors. But, this is something we can iterate on, so maybe start with fewer implementation options and improve as needed.

Overall, I'm not super happy with this direction yet. So, any proposals are more than welcome. I'm hoping I can get this flushed out within the next 2 weeks.

**Comment by jaredcnance** [comment]
I have a working example of this on the unstable branch [here](https://github.com/Research-Institute/json-api-dotnet-core/tree/unstable/src/Examples/ReportsExample).

From an implementation perspective, I think this is okay. Your service simply [implements the interfaces you need](https://github.com/Research-Institute/json-api-dotnet-core/blob/unstable/src/Examples/ReportsExample/Services/ReportService.cs#L7) and you pass the specific service to the base constructor [in your controller](https://github.com/Research-Institute/json-api-dotnet-core/blob/unstable/src/Examples/ReportsExample/Controllers/ReportsController.cs#L16-L17).

**Comment by williamwong** [comment]
If your service implements more than one of the interfaces, what to you pass into controller?

I see that you've got a whole hierarchy of interface inheritance, so I guess the intention is that that should cover most reasonable permutations of create/update/get/delete, so you would choose IGetAllService, IResourceCmdService, or IResourceService, etc. as needed, right? And your service should rarely implement more than one of the interfaces?

**Comment by jaredcnance** [comment]
@williamwong if your service is implementing multiple interfaces, but not enough to fully implement [IResourceCmdService](https://github.com/Research-Institute/json-api-dotnet-core/blob/unstable/src/JsonApiDotNetCore/Services/Contract/IResourceCmdService.cs) or [IResourceQueryService](https://github.com/Research-Institute/json-api-dotnet-core/blob/unstable/src/JsonApiDotNetCore/Services/Contract/IResourceQueryService.cs), you first need to inject the service for each implemented interface. Using Autofac, as an example, this is simply:

```csharp
public class MyResourceService : ICreateService<MyResource>, IDeleteService<MyResource> {
 //...
}

public class Startup {
  public IServiceProvider ConfigureServices(IServiceCollection services) {
    // ...
    builder.RegisterType<MyResourceService>().AsImplementedInterfaces();
    // ...
  }
}
```

Then in your controller:

```csharp
public class MyResourcesController : BaseJsonApiController<MyResource, int> {
    public MyResourcesController(
        IJsonApiContext jsonApiContext, 
        ICreateService<MyResource> create,
        IDeleteService<MyResource> delete) 
    : base(
        jsonApiContext, 
        create: create, // <--- pass the services to the base controller using named optional parameters
        delete: delete) { }

    [HttpPost]
    public override async Task<IActionResult> PostAsync([FromBody] MyResource entity) 
        => await base.PostAsync(entity);

    [HttpDelete("{id}")]
    public override async Task<IActionResult>DeleteAsync(int id) 
        => await base.DeleteAsync(id);
}
```

**Comment by williamwong** [comment]
Thanks for the explanation @jaredcnance . This looks great!
