### ISSUE TITLE
Optional relationships

### ISSUE THREAD

**Issue by SonicGD** [Research-Institute/json-api-dotnet-core#40]
Hi. I have optional relationships in my models. 
```csharp
class Model : Identifiable<int>
{
  public override int Id {get;set;}
  public int? FooId {get;set;}
  public int? BarId {get;set;}
  public int? BazId {get;set;}

  public virtual A Foo {get;set;}
  public virtual B Bar {get;set;}
  public virtual C Baz {get;set;}
}
```
For every model only one of this relationships can exists. When i do query like this
```
http://localhost:5000/models?include=foo,bar,baz
```
i catch exception:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Object.GetType()
   at JsonApiDotNetCore.Builders.DocumentBuilder._getRelationship(Object entity, String relationshipName)
   at JsonApiDotNetCore.Builders.DocumentBuilder.<>c__DisplayClass8_0.<_addRelationships>b__0(Relationship r)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at JsonApiDotNetCore.Builders.DocumentBuilder._getData(ContextEntity contextEntity, IIdentifiable entity)
   at JsonApiDotNetCore.Builders.DocumentBuilder.Build(IEnumerable`1 entities)
   at JsonApiDotNetCore.Serialization.JsonApiSerializer._serializeDocuments(Object entity, IJsonApiContext jsonApiContext)
   at JsonApiDotNetCore.Formatters.JsonApiOutputFormatter.<WriteAsync>d__1.MoveNext()
```

As i understand, problem is here - https://github.com/Research-Institute/json-api-dotnet-core/blob/master/src/JsonApiDotNetCore/Builders/DocumentBuilder.cs#L209 cause `entity` is null.

Should there be check for null? I can make PR if needed.

**Comment by jaredcnance** [comment]
Yeah I also discovered this yesterday while working on #21. I've got a fix in place (see #41 specifically 2b3aecb96d8aed717e6fb2d3165f78730ff77c49).

I will get this PR finished today, also please note that there is a breaking change involved that will remove the requirement for you to override the `Id` property. So, your new model would look like:

```
class Model : Identifiable
{
  public int? FooId {get;set;}
  public int? BarId {get;set;}
  public int? BazId {get;set;}

  public virtual A Foo {get;set;}
  public virtual B Bar {get;set;}
  public virtual C Baz {get;set;}
}
```

**Comment by jaredcnance** [comment]
I went ahead and deployed these changes to MyGet. If you'd like to go ahead and integrate these changes, just add the feed to your NuGet.config file:

```xml
<add key="ResearchInstituteMyGet" value="https://www.myget.org/F/research-institute/api/v3/index.json" />
```

and update project.json:

```json
"JsonApiDotnetCore": "1.0.0-beta1-0041"
```

**Comment by SonicGD** [comment]
I've tried it and now it works, thank you.

>also please note that there is a breaking change involved that will remove the requirement for you to override the Id property

So if i need to add some annotations like Key or Column, i can do

```csharp
[Key]
[Column("member_id")]
public new int Id {get;set;}
```
right?

**Comment by jaredcnance** [comment]
That should work. Would you prefer a solution that allows you to override? I'm open to making the Id property `virtual`.

**Comment by SonicGD** [comment]
> That should work.

Yes it does.

> Would you prefer a solution that allows you to override?

I think `virtual`/`override` looks more appropriate
