### ISSUE TITLE
Hard dependency to MVC setup

### ISSUE THREAD

**Issue by JanMattner** [Research-Institute/json-api-dotnet-core#71]
Currently, MVC is setup inside the JSONAPI Framework's own calls and there is no possibility to customize the MVC setup e.g. with custom options. There should be a possibility to customize the calls or do them on one's own.

Particularly: [IApplicationBuilderExtension](https://github.com/Research-Institute/json-api-dotnet-core/blob/2c7d07f58f408c8081cbeb271b1b8fcce05db6b1/src/JsonApiDotNetCore/Extensions/IApplicationBuilderExtensions.cs#L12) and [IServiceCollectionExtensions](https://github.com/Research-Institute/json-api-dotnet-core/blob/2c7d07f58f408c8081cbeb271b1b8fcce05db6b1/src/JsonApiDotNetCore/Extensions/IServiceCollectionExtensions.cs#L36-L40)

... working on it...

**Comment by JanMattner** [comment]
Okay I just realized that the dependency in IServiceCollectionExtensions is actually not that hard since you can basically do everything on your own what's done in _addInternals:

```c#
            services.AddJsonApiInternals<TContext>(jsonApiOptions);
            services.AddMvc()
                .AddMvcOptions(opt => {
                    opt.Filters.Add(typeof(JsonApiExceptionFilter));
                    opt.SerializeAsJsonApi(jsonApiOptions);
                });
```

`AddJsonApiInternals`, `SerializeAsJsonApi` and `JsonApiExceptionFilter` are all public, thus we can just replicate that code if necessary. However, it would be more convenient to have a method that just takes an IMvcBuilder as input.

What do you think?

**Comment by jaredcnance** [comment]
> AddJsonApiInternals, SerializeAsJsonApi and JsonApiExceptionFilter are all public, thus we can just replicate that code
I think that was my original intent for extensibility

> However, it would be more convenient to have a method that just takes an IMvcBuilder as input.

I think this is a good solution

**Comment by jaredcnance** [comment]
@JanMattner did you want to add an overload for the services? or I can do it tonight. i'd like to get both of these in before pushing develop into master

**Comment by JanMattner** [comment]
@jaredcnance No sorry, probably can't do it this weekend
