### ISSUE TITLE
Get error when I try to filter by Guid

### ISSUE THREAD

**Issue by nialljt1** [Research-Institute/json-api-dotnet-core#81]
For example when I try to filter by a guid like below
?filter[bookingId]=bff69e53-0275-4ba2-fde0-08d45592e5f1
I get the an error
Invalid cast from 'System.String' to 'System.Guid'

**Comment by jaredcnance** [comment]
@nialljt1 thanks for opening the issue! #82 addresses this and adds tests around it. I hope to bring develop into master by tomorrow, but you can get the fix via the [pre-release feed](https://www.myget.org/feed/research-institute/package/nuget/JsonApiDotNetCore) now `1.3.0-alpha1-0095`
