### ISSUE TITLE
Filter by attribute of related entity

### ISSUE THREAD

**Issue by nialljt1** [Research-Institute/json-api-dotnet-core#85]
Maybe this is possible already but it would be great to be able to filter by an attribute of a related entity
Maybe, have something like 
bookings?include=status&filter[starting-at]=le:2017-01-01&filter[status.name]=eq:active

**Comment by jaredcnance** [comment]
@nialljt1 this is not currently supported. i'll take some time this week to think about the best way to implement it and try to get it in this weekend.

**Comment by nialljt1** [comment]
Hi Jared,

Thanks for the response and thanks for all the good work.

Niall

**Comment by jaredcnance** [comment]
@nialljt1 this has been merged into the pre-release package [1.3.2-alpha1-0101](https://www.myget.org/feed/research-institute/package/nuget/JsonApiDotNetCore). Can you pull this version and verify it fixes your issue?

**Comment by nialljt1** [comment]
Hi Jared,

I pulled this version and confirmed that this allows me to filter by a
related entity and thus fixed my issue.

Thank you very much.
