### ISSUE TITLE
Inconsistency for dasherized attributes

### ISSUE THREAD

**Issue by JanMattner** [Research-Institute/json-api-dotnet-core#93]
If I have a client entity definition as follows:

```csharp
public class Client : Identifiable
{
        [Attr("clientName")]
        public string ClientName { get; set; }
}
```

I expect that the attribute is everywhere referenced as "clientName". However, when POSTing a new client, I am forced to use the dasherized version of it:

```json
{
  "data": {
    "type": "clients",
    "attributes": {
      "client-name": "Foo Bar"
  }
}
```

However, the response of that and a normal GET request uses the non-dasherized version:

```json
{
  "data": {
    "type": "clients",
    "id": "8",
    "attributes": {
      "clientName": "Foo Bar"
    },
  }
}
```

I am forced to do that due to this [line in the JsonApiDeSerialization.cs](https://github.com/Research-Institute/json-api-dotnet-core/blob/master/src/JsonApiDotNetCore/Serialization/JsonApiDeSerializer.cs#L98)

I expect that the attribute names defined via the `Attr` attribute are used throughout the framework.

**Comment by jaredcnance** [comment]
Thanks for opening this. I discovered a few other related issues while working on #89. Once I get that wrapped up, I'm going to kick over to this and push them out in the same release.

**Comment by jaredcnance** [comment]
Outstanding issues:
- [ ] Provide a clearer way to specify the routing convention. Possible options include:
  - introduce a flag on JsonApiOptions that would allow users to disable the DasherizedRoutingConvention globally
  - provide attributes that could decorate the controller to disable the routing convention
  - check if the user has supplied a specific route through the RouteAttribute and if so, then disable the convention.

- [ ] Make a decision on how to handle mismatched (?) routing (todo-items-test -> todo-items):
```csharp
[Route("/todo-items-test")] 
public class TodoItemsTestController : JsonApiController<TodoItem> 
{ // ... 
}
```
